# Generated by Django 5.1 on 2024-08-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Bot name (Chat LLM)", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="slug",
            field=models.CharField(
                db_index=True,
                help_text="Can be a model id hosted on the Hugging Face Hub, e.g. `meta-llama/Meta-Llama-3-8B-Instruct` or a URL to a deployed Inference Endpoint.",
                max_length=128,
                unique=True,
            ),
        ),
    ]
