# Generated by Django 5.1 on 2024-08-18 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_alter_bot_name_alter_bot_slug"),
        ("chats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="bot",
            field=models.ForeignKey(
                help_text="Chatbot (Chat LLM)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="bots.bot",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                help_text="User",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
