# Generated by Django 5.1 on 2024-08-18 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_alter_bot_name_alter_bot_slug"),
        ("chats", "0002_alter_chat_bot_alter_chat_user"),
        ("messages", "0002_alter_message_bot_alter_message_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="bot",
            field=models.ForeignKey(
                blank=True,
                help_text="Bot",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="bots.bot",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                help_text="Chat",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chats.chat",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(
                db_index=True, help_text="Message content", max_length=4096
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
