name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Clone botland
        run: |
          git clone https://github.com/youzarsiph/botland
          
      - name: Install Dependencies
        run: |
          cp botland/requirements.txt requirements.txt
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create a Django project and configure settings
        run: |
          python -m django startproject mysite
          cp -r botland mysite/botland
          cd mysite
          echo "INSTALLED_APPS += ['botland', 'botland.bots', 'botland.chats', 'botland.messages', 'botland.users', 'rest_framework']" >> mysite/settings.py
          echo "AUTH_USER_MODEL = 'users.User'" >> mysite/settings.py

      - name: Configure URLConf
        run: |
          cd mysite
          echo "from django.urls import include" >> mysite/urls.py
          echo "urlpatterns += [path('', include('botland.urls'))]" >> mysite/urls.py

      - name: Run Migrations, System checks and test
        run: |
          python -m poetry shell
          cd mysite
          python manage.py migrate
          python manage.py check
          python manage.py test
