name: Ruff

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install ruff

      - name: Analyzing the code with Ruff
        run: |
          source .venv/bin/activate
          ruff check .
